Pandas Learning

In [5]:
import pandas as pd

Introduction to Dataframe

In [6]:
#We initialize datas in pandas:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["x","y","z"])

In [7]:
'''df.head(1) Accessing first 2 row
df.head(0) Accessing the row 0 
df.head(3) Accessing data upto row 3'''

df.head() #Accessing all elements in the dataframe
#df.head(2)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [8]:
#df.tail(1)
df.tail(2)

   A  B  C
y  4  5  6
z  7  8  9

In [9]:
df.info()#Descritption of our dataframe

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [10]:
df.describe()#meaningful information of data of individual columns

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [11]:
df.nunique()#tota number of unique values in each column

A    3
B    3
C    3
dtype: int64

In [12]:
df['A'].unique()#Unique elements in specific column

array([1, 4, 7])

In [13]:
df['A'].nunique()#total no of unique values in specific column

3

In [14]:
df.shape #shape of dataframe

(3, 3)

In [15]:
df.size #size of dataframe

9

**Loading in Dataframes form files**

In [16]:
coffee=pd.read_csv('./coffee.csv')

In [17]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [18]:
results=pd.read_csv('./data/results.csv')
#('./folder_name/file_name')

In [19]:
results.head(2)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN

In [ ]:
olympics_data=pd.read_excel('./data/olympics-data.xlsx') #Accessing excel file

In [29]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
results=pd.read_parquet('./data/results.parquet')#Accessing using parquet file which is compartively faster in accessing than csv and excel file.

In [34]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN